services:
  client-app:
    container_name: client-manager-service
    image: ghcr.io/viclegend/connection-vault:latest
    ports:
      - "${HOST_PORT}:8080"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped