services:
  client-app:
    image: client-manager-app:v6
    container_name: my-client-db
    ports:
      - "${HOST_PORT}:8080"  # 由.env 注入
    volumes:
      - ./data:/app/data
    env_file:
      - .env                 # 載入.env 環境變數檔
    restart: unless-stopped